// src/renderer/src/layout/DevicePanel.vue
<template>
  <div class="device-panel">
    <!-- 面板头部 -->
    <div class="panel-header">
      <t-button 
        variant="text" 
        shape="square"
        @click="$emit('toggle')"
      >
        <t-icon :name="collapsed ? 'chevron-right' : 'chevron-left'" />
      </t-button>
      
      <span v-if="!collapsed" class="panel-title">设备列表</span>
      
      <t-button 
        v-if="!collapsed"
        variant="text" 
        shape="square"
        size="small"
        @click="refreshDevices"
      >
        <t-icon name="refresh" />
      </t-button>
    </div>

    <!-- 设备列表 -->
    <div class="device-list-container">
      <t-empty
        v-if="devices.length === 0"
        description="暂无设备"
        size="small"
      />
      
      <t-list v-else size="small" split>
        <t-list-item
          v-for="device in devices"
          :key="device.id"
          :class="['device-item', { active: device.id === activeDeviceId }]"
          @click="selectDevice(device.id)"
        >
          <t-list-item-meta
            :title="collapsed ? '' : device.name"
            :description="collapsed ? '' : device.osVersion"
          >
            <template #avatar>
              <t-avatar 
                shape="circle" 
                :style="{ backgroundColor: getDeviceColor(device.type) }"
              >
                <t-icon :name="getDeviceIcon(device.type)" />
              </t-avatar>
            </template>
          </t-list-item-meta>

          <template #action>
            <t-tag 
              v-if="!collapsed"
              :theme="getStatusTheme(device.status)" 
              variant="light"
              size="small"
            >
              {{ getStatusText(device.status) }}
            </t-tag>
          </template>
        </t-list-item>
      </t-list>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useDevice } from '../composables/useDevice'
import type { DeviceType, DeviceStatus } from '../types'

defineProps<{
  collapsed: boolean
}>()

defineEmits<{
  toggle: []
}>()

const { devices, activeDeviceId, refreshDevices, selectDevice } = useDevice()

function getDeviceIcon(type: DeviceType) {
  const icons: Record<DeviceType, string> = {
    android: 'logo-android',
    ios: 'logo-apple',
    web: 'internet',
    ohos: 'logo-huawei'
  }
  return icons[type] || 'device'
}

function getDeviceColor(type: DeviceType) {
  const colors: Record<DeviceType, string> = {
    android: '#10B981',
    ios: '#3B82F6',
    web: '#F59E0B',
    ohos: '#000000'
  }
  return colors[type] || '#6B7280'
}

function getStatusTheme(status: DeviceStatus) {
  const themes: Record<DeviceStatus, string> = {
    connected: 'success',
    disconnected: 'default',
    busy: 'warning'
  }
  return themes[status]
}

function getStatusText(status: DeviceStatus) {
  const texts: Record<DeviceStatus, string> = {
    connected: '已连接',
    disconnected: '未连接',
    busy: '忙碌'
  }
  return texts[status]
}
</script>

<style scoped>
.device-panel {
  height: 100%;
  display: flex;
  flex-direction: column;
  background-color: var(--td-bg-color-container);
}

.panel-header {
  height: 48px;
  display: flex;
  align-items: center;
  padding: 0 12px;
  border-bottom: 1px solid var(--td-border-color);
  gap: 8px;
}

.panel-title {
  flex: 1;
  font-size: 14px;
  font-weight: 500;
  color: var(--td-text-color-primary);
}

.device-list-container {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}

.device-item {
  cursor: pointer;
  border-radius: 6px;
  transition: background-color 0.2s;
}

.device-item:hover {
  background-color: var(--td-bg-color-container-hover);
}

.device-item.active {
  background-color: rgba(59, 130, 246, 0.15);
}
</style>

// src/renderer/src/layout/DevicePanel.tsx
import { List, Badge, Tag, Typography, Empty, Button, Tooltip } from 'antd'
import { 
  MobileOutlined, 
  AppleOutlined,
  DesktopOutlined,
  WifiOutlined,
  DisconnectOutlined,
  LoadingOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  ReloadOutlined,
} from '@ant-design/icons'
import { Device } from '../types'
import './DevicePanel.css'

const { Text } = Typography

interface DevicePanelProps {
  devices: Device[]
  activeDeviceId: string | null
  onSelectDevice: (deviceId: string) => void
  collapsed?: boolean
  onToggleCollapse?: () => void
}

const getDeviceIcon = (type: Device['type']) => {
  const iconStyle = { fontSize: 20 }
  switch (type) {
    case 'android':
      return <MobileOutlined style={{ ...iconStyle, color: 'var(--color-success)' }} />
    case 'ios':
      return <AppleOutlined style={{ ...iconStyle, color: 'var(--color-primary)' }} />
    case 'web':
      return <DesktopOutlined style={{ ...iconStyle, color: 'var(--color-warning)' }} />
    default:
      return <MobileOutlined style={iconStyle} />
  }
}

const getStatusIcon = (status: Device['status']) => {
  switch (status) {
    case 'connected':
      return <Badge status="success" />
    case 'busy':
      return <LoadingOutlined style={{ color: 'var(--color-primary)' }} spin />
    case 'disconnected':
      return <DisconnectOutlined style={{ color: 'var(--color-error)' }} />
    default:
      return <Badge status="default" />
  }
}

const getStatusColor = (status: Device['status']): string => {
  switch (status) {
    case 'connected':
      return 'success'
    case 'busy':
      return 'processing'
    case 'disconnected':
      return 'error'
    default:
      return 'default'
  }
}

function DevicePanel({ 
  devices, 
  activeDeviceId, 
  onSelectDevice,
  collapsed = false,
  onToggleCollapse,
}: DevicePanelProps): JSX.Element {
  const connectedCount = devices.filter(d => d.status === 'connected').length

  if (collapsed) {
    return (
      <div className="device-panel device-panel--collapsed">
        <div className="device-panel-header device-panel-header--collapsed">
          <Tooltip title="Expand" placement="right">
            <Button
              type="text"
              icon={<MenuUnfoldOutlined />}
              onClick={onToggleCollapse}
              style={{ color: 'var(--color-text-secondary)' }}
            />
          </Tooltip>
        </div>
        
        <div className="device-list-collapsed">
          {devices.map(device => (
            <Tooltip key={device.id} title={device.name} placement="right">
              <div
                className={`device-item-collapsed ${activeDeviceId === device.id ? 'active' : ''}`}
                onClick={() => onSelectDevice(device.id)}
              >
                <div className="device-icon-collapsed">
                  {getDeviceIcon(device.type)}
                </div>
                {device.status === 'connected' && (
                  <div className="device-status-indicator" />
                )}
              </div>
            </Tooltip>
          ))}
          
          <Tooltip title="Refresh devices" placement="right">
            <Button
              type="text"
              icon={<ReloadOutlined />}
              style={{ 
                width: 48, 
                height: 48, 
                marginTop: 8,
                color: 'var(--color-text-secondary)',
              }}
              onClick={() => window.location.reload()}
            />
          </Tooltip>
        </div>
      </div>
    )
  }

  return (
    <div className="device-panel">
      <div className="device-panel-header">
        <div className="device-panel-header-top">
          <div className="device-panel-title">
            <Text strong style={{ color: 'var(--color-text-primary)', fontSize: 16 }}>
              Devices
            </Text>
            <Tag color="default" style={{ marginLeft: 8, fontSize: 12 }}>
              {devices.length}
            </Tag>
          </div>
          
          <div className="device-panel-actions">
            <Tooltip title="Refresh">
              <Button
                type="text"
                size="small"
                icon={<ReloadOutlined />}
                onClick={() => window.location.reload()}
                style={{ color: 'var(--color-text-secondary)' }}
              />
            </Tooltip>
            
            <Tooltip title="Collapse">
              <Button
                type="text"
                size="small"
                icon={<MenuFoldOutlined />}
                onClick={onToggleCollapse}
                style={{ color: 'var(--color-text-secondary)' }}
              />
            </Tooltip>
          </div>
        </div>
        
        <div className="device-panel-subtitle">
          <WifiOutlined style={{ marginRight: 6, color: 'var(--color-success)' }} />
          <Text type="secondary" style={{ fontSize: 12 }}>
            {connectedCount} connected
          </Text>
        </div>
      </div>

      <div className="device-list-container">
        {devices.length === 0 ? (
          <Empty
            description={
              <Text type="secondary">No devices found</Text>
            }
            image={Empty.PRESENTED_IMAGE_SIMPLE}
            style={{ marginTop: 40, opacity: 0.7 }}
          />
        ) : (
          <List
            className="device-list"
            dataSource={devices}
            renderItem={(device) => (
              <List.Item
                className={`device-item ${activeDeviceId === device.id ? 'active' : ''}`}
                onClick={() => onSelectDevice(device.id)}
              >
                <List.Item.Meta
                  avatar={
                    <div className="device-icon">
                      {getDeviceIcon(device.type)}
                    </div>
                  }
                  title={
                    <div className="device-item-title">
                      <Text style={{ color: 'var(--color-text-primary)' }} ellipsis>
                        {device.name}
                      </Text>
                      {getStatusIcon(device.status)}
                    </div>
                  }
                  description={
                    <div className="device-item-description">
                      <div className="device-item-tags">
                        <Tag 
                          color={getStatusColor(device.status)}
                          style={{ fontSize: 11 }}
                        >
                          {device.status}
                        </Tag>
                        
                        {device.resolution && (
                          <Text type="secondary" style={{ fontSize: 11 }}>
                            {device.resolution}
                          </Text>
                        )}
                      </div>
                      
                      {device.osVersion && (
                        <Text type="secondary" style={{ fontSize: 11, marginTop: 4 }}>
                          {device.osVersion}
                        </Text>
                      )}
                    </div>
                  }
                />
              </List.Item>
            )}
          />
        )}
      </div>
    </div>
  )
}

export default DevicePanel
