// src/renderer/src/layout/TitleBar.tsx
import React, { useState, useEffect } from 'react'
import { Layout, Button, Space, Tooltip } from 'antd'
import { 
  MinusOutlined, 
  BorderOutlined,
  FullscreenExitOutlined,
  CloseOutlined,
  AppstoreOutlined
} from '@ant-design/icons'
import './TitleBar.css'

const { Header } = Layout

// Extend window interface
declare global {
  interface Window {
    api?: {
      minimizeWindow: () => void
      toggleMaximizeWindow: () => void
      closeWindow: () => void
      onWindowStateChange: (callback: (state: { maximized: boolean }) => void) => void
    }
  }
}

function TitleBar(): JSX.Element {
  const [isMaximized, setIsMaximized] = useState(false)

  useEffect(() => {
    // Listen for window state changes
    window.api?.onWindowStateChange((state) => {
      setIsMaximized(state.maximized)
    })
  }, [])

  const handleMinimize = () => {
    window.api?.minimizeWindow()
  }

  const handleMaximize = () => {
    window.api?.toggleMaximizeWindow()
  }

  const handleClose = () => {
    window.api?.closeWindow()
  }

  return (
    <Header className="title-bar" style={{ 
      height: 40, 
      padding: '0 16px',
      background: '#1a1a2e',
      borderBottom: '1px solid rgba(255,255,255,0.1)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      // @ts-ignore
      WebkitAppRegion: "drag"
    } as unknown as React.CSSProperties}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <AppstoreOutlined style={{ fontSize: 20, color: '#1890ff' }} />
        <span style={{ 
          color: '#fff', 
          fontSize: 14, 
          fontWeight: 600,
          marginLeft: 8 
        }}>
          Omni Controller
        </span>
      </div>

      <Space style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}>
        <Tooltip title="Minimize">
          <Button
            type="text"
            icon={<MinusOutlined />}
            onClick={handleMinimize}
            style={{ color: '#fff' }}
          />
        </Tooltip>
        <Tooltip title={isMaximized ? 'Restore' : 'Maximize'}>
          <Button
            type="text"
            icon={isMaximized ? <FullscreenExitOutlined /> : <BorderOutlined />}
            onClick={handleMaximize}
            style={{ color: '#fff' }}
          />
        </Tooltip>
        <Tooltip title="Close">
          <Button
            type="text"
            icon={<CloseOutlined />}
            onClick={handleClose}
            style={{ color: '#fff' }}
            danger
          />
        </Tooltip>
      </Space>
    </Header>
  )
}

export default TitleBar

// src/renderer/src/layout/TitleBar.vue
<template>
  <div class="title-bar">
    <div class="title-bar-content">
      <div class="window-controls">
        <t-button 
          variant="text" 
          shape="square"
          size="small"
          @click="minimizeWindow"
        >
          <t-icon name="minus" />
        </t-button>
        <t-button 
          variant="text" 
          shape="square"
          size="small"
          @click="toggleMaximize"
        >
          <t-icon :name="isMaximized ? 'fullscreen-exit' : 'fullscreen'" />
        </t-button>
        <t-button 
          variant="text" 
          shape="square"
          size="small"
          theme="danger"
          @click="closeWindow"
        >
          <t-icon name="close" />
        </t-button>
      </div>
      
      <div class="app-title">
        <t-icon name="logo" class="app-icon" />
        <span>Omni Controller</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

const isMaximized = ref(false)

function minimizeWindow() {
  window.api?.minimizeWindow?.()
}

function toggleMaximize() {
  window.api?.toggleMaximizeWindow?.()
}

function closeWindow() {
  window.api?.closeWindow?.()
}

onMounted(() => {
  // 监听窗口状态变化
  window.api?.onWindowStateChange?.((state: { maximized: boolean }) => {
    isMaximized.value = state.maximized
  })
})
</script>

<style scoped>
.title-bar {
  height: 40px;
  background-color: var(--td-bg-color-container);
  border-bottom: 1px solid var(--td-border-color);
  -webkit-app-region: drag;
  display: flex;
  align-items: center;
  padding: 0 12px;
}

.title-bar-content {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}

.window-controls {
  display: flex;
  gap: 8px;
  -webkit-app-region: no-drag;
}

.app-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  font-weight: 500;
  color: var(--td-text-color-primary);
}

.app-icon {
  font-size: 20px;
  color: var(--td-brand-color);
}
</style>
